/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x17361401
 */
public class HouseGUI extends javax.swing.JFrame {

    Project1 e;
   private ArrayList<Central> array=new ArrayList();
    private ArrayList<South> array1=new ArrayList();
     private ArrayList<North> array2=new ArrayList();
    String mtype;
    String mlocation;
    String mcost;
     String location1;
    String location2;
    String cost1;
    String cost2;
    String atype;
    String location3;
    String cost3;
    String input;
    String type4;
    String cost4;
    String location4;
    
    int count;
    /**
     * Creates new form ModuleGUI
     */
    public HouseGUI() {
        initComponents();
        tutorial1Lbl.setVisible(false);
        tutorial2Lbl.setVisible(false);
        day1Lbl.setVisible(false);
        day1TF.setVisible(false);
        day2Lbl.setVisible(false);
        day2TF.setVisible(false);
        time1Lbl.setVisible(false);
        time1TF.setVisible(false);
        time2Lbl.setVisible(false);
        time2TF.setVisible(false);
        labLbl.setVisible(false);
        day3Lbl.setVisible(false);
        day3TF.setVisible(false);
        time3Lbl.setVisible(false);
        time3TF.setVisible(false);
        anameLbl.setVisible(false);
         anameTF.setVisible(false);
         hnameLbl.setVisible(false);
         hnameTF.setVisible(false);
          time4Lbl.setVisible(false);
        time4TF.setVisible(false);
        day4Lbl.setVisible(false);
        day4TF.setVisible(false);
        artLbl.setVisible(false);
         readFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        lnameLbl = new javax.swing.JLabel();
        ldayLbl = new javax.swing.JLabel();
        ltimeLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        lnameTF = new javax.swing.JTextField();
        ldayTF = new javax.swing.JTextField();
        ltimeTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        tutorial1Lbl = new javax.swing.JLabel();
        day1Lbl = new javax.swing.JLabel();
        time1Lbl = new javax.swing.JLabel();
        day1TF = new javax.swing.JTextField();
        time1TF = new javax.swing.JTextField();
        tutorial2Lbl = new javax.swing.JLabel();
        day2Lbl = new javax.swing.JLabel();
        day2TF = new javax.swing.JTextField();
        time2Lbl = new javax.swing.JLabel();
        time2TF = new javax.swing.JTextField();
        anameLbl = new javax.swing.JLabel();
        anameTF = new javax.swing.JTextField();
        labLbl = new javax.swing.JLabel();
        time3TF = new javax.swing.JTextField();
        day3Lbl = new javax.swing.JLabel();
        time3Lbl = new javax.swing.JLabel();
        day3TF = new javax.swing.JTextField();
        ComboBox = new javax.swing.JComboBox<>();
        artLbl = new javax.swing.JLabel();
        hnameLbl = new javax.swing.JLabel();
        hnameTF = new javax.swing.JTextField();
        day4Lbl = new javax.swing.JLabel();
        day4TF = new javax.swing.JTextField();
        time4Lbl = new javax.swing.JLabel();
        time4TF = new javax.swing.JTextField();
        Surveybtn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("House");

        nameLbl.setText("House Name");

        lnameLbl.setText("Location");

        ldayLbl.setText("House Type");

        ltimeLbl.setText("Price");

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        tutorial1Lbl.setText("Upstairs:");

        day1Lbl.setText("No. of Bathrooms:");

        time1Lbl.setText("No. of Bedrooms:");

        tutorial2Lbl.setText("Downstairs:");

        day2Lbl.setText("No.of Bathrooms:");

        time2Lbl.setText("No. of other rooms:");

        anameLbl.setText("No. of Bathrooms:");

        labLbl.setText("Rooms of House:");

        day3Lbl.setText("No. of Bedrooms: ");

        time3Lbl.setText("No. of other rooms:");

        ComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click Here", "2 Storey House", "1 Storey House" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        artLbl.setText("Other");

        hnameLbl.setText("Other rooms");

        day4Lbl.setText("Bathrooms");

        time4Lbl.setText("Bedrooms");

        Surveybtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Surveybtn.setText("Survey");
        Surveybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurveybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(day1Lbl)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(day1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(day2Lbl)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(day2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(time2Lbl)
                                                        .addGap(14, 14, 14)
                                                        .addComponent(time2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(time1Lbl)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(time1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(nameLbl)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ldayLbl)
                                                        .addComponent(ltimeLbl)
                                                        .addComponent(lnameLbl))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                        .addComponent(ldayTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ltimeTF, javax.swing.GroupLayout.Alignment.LEADING)))))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tutorial2Lbl)
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tutorial1Lbl)
                                .addGap(166, 166, 166)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Surveybtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addComponent(displayBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(artLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(day4Lbl)
                                .addGap(18, 18, 18)
                                .addComponent(day4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(time4Lbl)
                                .addGap(18, 18, 18)
                                .addComponent(time4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(hnameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hnameTF))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(anameLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(day3Lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(day3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(time3Lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(time3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(labLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBtn)
                        .addGap(16, 16, 16)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameLbl)
                            .addComponent(lnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ldayLbl)
                            .addComponent(ldayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltimeLbl)
                            .addComponent(ltimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(displayBtn)
                        .addGap(11, 11, 11)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Surveybtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tutorial1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day1Lbl)
                            .addComponent(day1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time1Lbl)
                            .addComponent(time1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tutorial2Lbl)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day2Lbl)
                            .addComponent(day2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time2Lbl)
                            .addComponent(time2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(labLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anameLbl)
                    .addComponent(anameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day3Lbl)
                    .addComponent(day3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time3Lbl)
                    .addComponent(time3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(artLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hnameLbl)
                    .addComponent(hnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day4Lbl)
                    .addComponent(day4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time4Lbl)
                    .addComponent(time4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
         if(e instanceof North){
            e=new North();
            mtype=nameTF.getText();
   mlocation=ldayTF.getText();
    mcost=ltimeTF.getText();
     location4=day4TF.getText();
    cost4=time4TF.getText();
   type4=hnameTF.getText();
   
   e.setType(mtype);
   e.setLocation(mlocation);
   e.setCost(mcost);
   ((North)e).setLocation4(location4);
   ((North)e).setCost4(cost4);
   ((North)e).setType4(type4);
    array2.add((North)e);
writeToFile();
        }
        
        else if(e instanceof Central){
            e=new Central();
            mtype=nameTF.getText();
   mlocation=ldayTF.getText();
    mcost=ltimeTF.getText();
     location1=day1TF.getText();
   location2=day2TF.getText();
    cost1=time1TF.getText();
   cost2=time2TF.getText();
   
   e.setType(mtype);
   e.setLocation(mlocation);
   e.setCost(mcost);
   ((Central)e).setLocation1(location1);
   ((Central)e).setLocation2(location2);
   ((Central)e).setCost1(cost1);
   ((Central)e).setCost2(cost2);
    array.add((Central)e);
writeToFile();
        }
        
        else  if(e instanceof South){
            e=new South();
            mtype=nameTF.getText();
   mlocation=ldayTF.getText();
    mcost=ltimeTF.getText();
     location3=day3TF.getText();
   atype=anameTF.getText();
    cost3=time3TF.getText();
   
   
   e.setType(mtype);
   e.setLocation(mlocation);
   e.setCost(mcost);
   ((South)e).setType3(atype);
   ((South)e).setLocation3(location3);
   ((South)e).setCost3(cost3);
   
    array1.add((South)e);
   writeToFile();
   
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        if(e instanceof Central){
        readFromFile();
            for(Project1 x:array){
            JOptionPane.showMessageDialog(null,x.printDetails());
            }
        }
       else if(e instanceof South){
        readFromFile();
            for(Project1 s:array1){
            JOptionPane.showMessageDialog(null,s.printDetails());
            }
            
    }//GEN-LAST:event_displayBtnActionPerformed
    
    else if(e instanceof North){
        readFromFile();
            for(Project1 p:array2){
            JOptionPane.showMessageDialog(null,p.printDetails());
            }
    }
    }
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        input=JOptionPane.showInputDialog(null,"Search by House Name.");
         readFromFile();
        
            for(Project1 x:array){
                 
                if(x.getType().equalsIgnoreCase(input)){
            JOptionPane.showMessageDialog(null,x.printDetails());
                }
            }

            for(Project1 s:array1){
                 
                if(s.getType().equalsIgnoreCase(input)){
            JOptionPane.showMessageDialog(null,s.printDetails());
                }
            }
            
            for(Project1 x:array2){
            
                if(x.getType().equalsIgnoreCase(input)){
                JOptionPane.showMessageDialog(null,x.printDetails());
                }
                
            }
        
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        readFromFile();readFromFile();        // TODO add your handling code here:
        
        if(e instanceof Central){
            count=array.size();
   if(nameTF.getText().equals("")||lnameTF.getText().equals("")||ldayTF.getText().equals("")||ltimeTF.getText().equals("")||day1TF.getText().equals("")||day2TF.getText().equals("")||time1TF.getText().equals("")||time2TF.getText().equals("")){
   JOptionPane.showMessageDialog(null,"Please Fill all text fields for 2 Storey House");
   }
   else if(array.size()==0){
   JOptionPane.showMessageDialog(null,"Your array is empty");
   }
   else{
   
       for(int i=0; i<count; i++){
       mtype=nameTF.getText();
   mlocation=ldayTF.getText();
    mcost=ltimeTF.getText();
     location1=day1TF.getText();
   location2=day2TF.getText();;
    cost1=time1TF.getText();
   cost2=time2TF.getText();
           if(array.get(i).getType().equals(mtype)&&array.get(i).getLocation().equals(mlocation)&&array.get(i).getCost().equals(mcost)&&array.get(i).getLocation().equals(location1)&&array.get(i).getLocation().equals(location2)&&array.get(i).getCost1().equals(cost1)&&array.get(i).getCost2().equals(cost2)){
           array.remove(i);
           writeToFile();
           count=count-1;
           JOptionPane.showMessageDialog(null,"Info remove from index "+i);
           break;
           }
           else if(i==count-1){
           JOptionPane.showMessageDialog(null,"Info not found");
           }
       }
   }
   
        }
        
        
        if(e instanceof South){
            count=array1.size();
   if(nameTF.getText().equals("")||lnameTF.getText().equals("")||ldayTF.getText().equals("")||ltimeTF.getText().equals("")||day3TF.getText().equals("")||time3TF.getText().equals("")||anameTF.getText().equals("")){
   JOptionPane.showMessageDialog(null,"Please Fill all text fields for 1 Storey House");
   }
   else if(array1.size()==0){
   JOptionPane.showMessageDialog(null,"Your array is empty");
   }
   else{
   
       for(int i=0; i<count; i++){
     
           mtype=nameTF.getText();
   mlocation=ldayTF.getText();
    mcost=ltimeTF.getText();
     location3=day3TF.getText();
   atype=anameTF.getText();
    cost3=time3TF.getText();
           
           if(array1.get(i).getType().equals(mtype)&&array1.get(i).getLocation().equals(mlocation)&&array1.get(i).getCost().equals(mcost)&&array1.get(i).getLocation3().equals(location3)&&array1.get(i).getCost3().equals(cost3)&&array1.get(i).getType3().equals(atype)){
           array1.remove(i);
           writeToFile();
           count=count-1;
           JOptionPane.showMessageDialog(null,"Info remove from index "+i);
           break;
           }
           else if(i==count-1){
           JOptionPane.showMessageDialog(null,"Info not found");
           }
       }
   }
   
        }
        
        if(e instanceof North){
            count=array2.size();
   if(nameTF.getText().equals("")||lnameTF.getText().equals("")||ldayTF.getText().equals("")||ltimeTF.getText().equals("")||day4TF.getText().equals("")||time4TF.getText().equals("")||hnameTF.getText().equals("")){
   JOptionPane.showMessageDialog(null,"Please Fill all text fields for 1 Storey House");
   }
   else if(array2.size()==0){
   JOptionPane.showMessageDialog(null,"Your array is empty");
   }
   else{
   
       for(int i=0; i<count; i++){
     
           mtype=nameTF.getText();
           mlocation=ldayTF.getText();
           mcost=ltimeTF.getText();
           location4=day4TF.getText();
           type4=hnameTF.getText();
           cost4=time4TF.getText();
           
           if(array2.get(i).getType().equals(mtype)&&array2.get(i).getLocation().equals(mlocation)&&array2.get(i).getCost().equals(mcost)&&array2.get(i).getLocation4().equals(location4)&&array2.get(i).getCost4().equals(cost4)&&array2.get(i).getType4().equals(type4)){
           array2.remove(i);
           writeToFile();
           count=count-1;
           JOptionPane.showMessageDialog(null,"Info remove from index "+i);
           break;
           }
           else if(i==count-1){
           JOptionPane.showMessageDialog(null,"Info not found");
           }
       }
   }
   
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
        if(ComboBox.getSelectedItem().equals("2 Storey House")){
       e=new Central();
          tutorial1Lbl.setVisible(true);
        tutorial2Lbl.setVisible(true);
        day1Lbl.setVisible(true);
        day1TF.setVisible(true);
        day2Lbl.setVisible(true);
        day2TF.setVisible(true);
        time1Lbl.setVisible(true);
        time1TF.setVisible(true);
        time2Lbl.setVisible(true);
        time2TF.setVisible(true);
        labLbl.setVisible(false);
        day3Lbl.setVisible(false);
        day3TF.setVisible(false);
        time3Lbl.setVisible(false);
        time3TF.setVisible(false);
        anameLbl.setVisible(false);
         anameTF.setVisible(false);
           hnameLbl.setVisible(false);
         hnameTF.setVisible(false);
          time4Lbl.setVisible(false);
        time4TF.setVisible(false);
        day4Lbl.setVisible(false);
        day4TF.setVisible(false);
        artLbl.setVisible(false);
        
        }
        
        else if(ComboBox.getSelectedItem().equals("Art")){
       
             tutorial1Lbl.setVisible(false);
        tutorial2Lbl.setVisible(false);
        day1Lbl.setVisible(false);
        day1TF.setVisible(false);
        day2Lbl.setVisible(false);
        day2TF.setVisible(false);
        time1Lbl.setVisible(false);
        time1TF.setVisible(false);
        time2Lbl.setVisible(false);
        time2TF.setVisible(false);
        labLbl.setVisible(false);
        day3Lbl.setVisible(false);
        day3TF.setVisible(false);
        time3Lbl.setVisible(false);
        time3TF.setVisible(false);
        anameLbl.setVisible(false);
         anameTF.setVisible(false);
         hnameLbl.setVisible(true);
         hnameTF.setVisible(true);
          time4Lbl.setVisible(true);
        time4TF.setVisible(true);
        day4Lbl.setVisible(true);
        day4TF.setVisible(true);
        artLbl.setVisible(true);
        }
        
        else if(ComboBox.getSelectedItem().equals("1 Storey House")){
        e=new South();
        tutorial1Lbl.setVisible(false);
        tutorial2Lbl.setVisible(false);
        day1Lbl.setVisible(false);
        day1TF.setVisible(false);
        day2Lbl.setVisible(false);
        day2TF.setVisible(false);
        time1Lbl.setVisible(false);
        time1TF.setVisible(false);
        time2Lbl.setVisible(false);
        time2TF.setVisible(false);
        labLbl.setVisible(true);
        day3Lbl.setVisible(true);
        day3TF.setVisible(true);
        time3Lbl.setVisible(true);
        time3TF.setVisible(true);
        anameLbl.setVisible(true);
         anameTF.setVisible(true);
           hnameLbl.setVisible(false);
         hnameTF.setVisible(false);
          time4Lbl.setVisible(false);
        time4TF.setVisible(false);
        day4Lbl.setVisible(false);
        day4TF.setVisible(false);
        artLbl.setVisible(false);
        
        }
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void SurveybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurveybtnActionPerformed
        // TODO add your handling code here:    
        this.dispose();
                new SurveyGUI().setVisible(true);
            
        
    }//GEN-LAST:event_SurveybtnActionPerformed
    
    public void writeToFile(){
    
        if(e instanceof Central){
        
            try{
            File f=new File("business.txt");
            FileOutputStream fStream=new FileOutputStream(f);
            ObjectOutputStream oStream=new ObjectOutputStream(fStream);
            oStream.writeObject(array);
            oStream.close();
            }
            catch(IOException r){
            System.out.println(r);
            }
        }
        
         if(e instanceof South){
             
        
            try{
            File f=new File("technical.txt");
            FileOutputStream fStream=new FileOutputStream(f);
            ObjectOutputStream oStream=new ObjectOutputStream(fStream);
            oStream.writeObject(array1);
            oStream.close();
            }
            catch(IOException r){
            System.out.println(r);
            }
        }
    
         if(e instanceof North){
             
        
            try{
            File f=new File("art.txt");
            FileOutputStream fStream=new FileOutputStream(f);
            ObjectOutputStream oStream=new ObjectOutputStream(fStream);
            oStream.writeObject(array2);
            oStream.close();
            }
            catch(IOException l){
            System.out.println(l);
            }
        }
    }
    
    public void readFromFile(){
    
     if(e instanceof Central){
        
            try{
            File f=new File("business.txt");
            FileInputStream fStream=new FileInputStream(f);
            ObjectInputStream oStream=new ObjectInputStream(fStream);
            array=(ArrayList<Central>)oStream.readObject();
            oStream.close();
            }
            catch(IOException |ClassNotFoundException i){
            System.out.println(i);
            }
        }
     
      if(e instanceof North){
        
            try{
            File f=new File("art.txt");
            FileInputStream fStream=new FileInputStream(f);
            ObjectInputStream oStream=new ObjectInputStream(fStream);
            array2=(ArrayList<North>)oStream.readObject();
            oStream.close();
            }
            catch(IOException |ClassNotFoundException i){
            System.out.println(i);
            }
        }
     
      if(e instanceof South){
        
            try{
            File f=new File("technical.txt");
            FileInputStream fStream=new FileInputStream(f);
            ObjectInputStream oStream=new ObjectInputStream(fStream);
            array1=(ArrayList<South>)oStream.readObject();
            oStream.close();
            }
            catch(IOException |ClassNotFoundException i){
            System.out.println(i);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/pl
        .html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HouseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Surveybtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel anameLbl;
    private javax.swing.JTextField anameTF;
    private javax.swing.JLabel artLbl;
    private javax.swing.JLabel day1Lbl;
    private javax.swing.JTextField day1TF;
    private javax.swing.JLabel day2Lbl;
    private javax.swing.JTextField day2TF;
    private javax.swing.JLabel day3Lbl;
    private javax.swing.JTextField day3TF;
    private javax.swing.JLabel day4Lbl;
    private javax.swing.JTextField day4TF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel hnameLbl;
    private javax.swing.JTextField hnameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labLbl;
    private javax.swing.JLabel ldayLbl;
    private javax.swing.JTextField ldayTF;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JLabel ltimeLbl;
    private javax.swing.JTextField ltimeTF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel time1Lbl;
    private javax.swing.JTextField time1TF;
    private javax.swing.JLabel time2Lbl;
    private javax.swing.JTextField time2TF;
    private javax.swing.JLabel time3Lbl;
    private javax.swing.JTextField time3TF;
    private javax.swing.JLabel time4Lbl;
    private javax.swing.JTextField time4TF;
    private javax.swing.JLabel tutorial1Lbl;
    private javax.swing.JLabel tutorial2Lbl;
    // End of variables declaration//GEN-END:variables
}
